### ISSUE TITLE
Keyer ignore Right Shift in Inserter

### ISSUE THREAD

**Issue by starryknight64** [YannThorimbert/Thorpy#6]
https://github.com/YannThorimbert/Thorpy/blob/2800dad17f16d4d3a2877e78609564077cc663f3/thorpy/miscgui/keyer.py#L89

Proposed change:
`    if pressed[K_LSHIFT] or pressed[K_RSHIFT]:  # handle caps`

**Comment by YannThorimbert** [comment]
Thanks, your suggestion has been added.
