### ISSUE TITLE
Cannot use transparency with image buttons

### ISSUE THREAD

**Issue by madhan001** [YannThorimbert/Thorpy#7]
Hi, Thank you for this library. I'm trying to use an image with rounded corners as a button using the make_image_button function and I'm unable to use them without having black colour in the areas that need to be transparent. I tried setting the alpha parameter to 0 and that doesn't seem to help it.

I'm using version 1.9 of Thorpy with Pygame 2.0 and python 3.6 on ubuntu 18.04.

![Screenshot from 2021-04-10 21-18-29](https://user-images.githubusercontent.com/6625194/114276570-cba56580-9a44-11eb-8303-dc024d077b14.png)

This is what the transparent corner looks like

**Comment by YannThorimbert** [comment]
Hi,

The expected behaviour is that black is interpreted as transparent if you give the argument colorkey=(0,0,0) when instantiating the button. If this does not work, could you provide the bit of code that poses problem ?
Thanks,
Yann

**Comment by madhan001** [comment]
> Hi,
> 
> The expected behaviour is that black is interpreted as transparent if you give the argument colorkey=(0,0,0) when instantiating the button. If this does not work, could you provide the bit of code that poses problem ?
> Thanks,
> Yann

Thanks, setting colorkey=(255,255,255) worked. May I know what exactly does this parameter do ?

**Comment by YannThorimbert** [comment]
It has the same effect as calling set_colorkey(some_color) method on the button's image. See https://www.pygame.org/docs/ref/surface.html#pygame.Surface.set_colorkey for more details.

**Comment by madhan001** [comment]
Thank you for assisting me. Closing this issue
